template = "https://github.com/giellalt/template-lang-und"
rev_id = 333
template_sha = "c0f15a905d69cb451762275644bf5c3133bfc106"

[replacements]
__GLOTTOLOG_ID__ = "pite1240"
__REPO__ = "lang-sje"
__UND2C__ = "sje"
__UNDEFINED__ = "Pite Sami"
__UND__ = "sje"
