template = "https://github.com/giellalt/template-lang-und"
rev_id = 312
template_sha = "aaa43738ed413bb95e9bd39f5489b35bab88cc4b"

[replacements]
__GLOTTOLOG_ID__ = "pite1240"
__REPO__ = "lang-sje"
__UND2C__ = "sje"
__UNDEFINED__ = "Pite Sami"
__UND__ = "sje"
