template = "https://github.com/giellalt/template-lang-und"
rev_id = 330
template_sha = "ca06c138bb7dc0942a15e60b710a001352e6ebde"

[replacements]
__GLOTTOLOG_ID__ = "pite1240"
__REPO__ = "lang-sje"
__UND2C__ = "sje"
__UNDEFINED__ = "Pite Sami"
__UND__ = "sje"
