[package]
name = "sje"
human_name = "Pite Sami"
version = "0.1.0"

# Table of speller tag -> filename to include in the bundle
# filenames depends on specific project
[spellers.sje]
filename = "sje-mobile.zhfst"

# Table of bundles to generated
# key is the type of bundle
# Windows speller bundle require a uuid for the installer
[bundles.speller_win]
package = "speller-sje"
platform = "windows"
uuid = "A7AAB3BF-7B9B-468E-8956-739857019D2F"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_macos]
pkg_id = "no.divvun.MacDivvun.sje"
package = "speller-sje"
platform = "macos"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_win_mso]
package = "speller-sje-mso"
platform = "windows"
uuid = "37BB0BBF-0791-4E15-9746-E232D8E20C60"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_mobile]
package = "speller-sje"
platform = "mobile"
repo = "https://pahkat.uit.no/main/"
